(function(){
const KEY='bholiSpicesCartV3',WA='917068013290',UPI='7985201404@pzw';
function get(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch(e){return[]}}function save(c){localStorage.setItem(KEY,JSON.stringify(c))}function money(n){return '₹'+Number(n).toLocaleString('en-IN')}
function add(id,name,weight,price){let c=get(),key=id+'-'+weight,x=c.find(i=>i.key===key);if(x)x.qty++;else c.push({key,id,name,weight,price:Number(price),qty:1});save(c);badge();toast(name+' ('+weight+') added to cart')}
function qty(key,d){let c=get(),x=c.find(i=>i.key===key);if(!x)return;x.qty+=d;c=c.filter(i=>i.qty>0);save(c);render();badge()}
function remove(key){save(get().filter(i=>i.key!==key));render();badge()}function clearCart(){save([]);render();badge()}
function totals(){let c=get(),sub=c.reduce((s,i)=>s+i.price*i.qty,0),del=sub===0||sub>=599?0:60;return{sub,del,total:sub+del}}
function badge(){let n=get().reduce((s,i)=>s+i.qty,0);document.querySelectorAll('[data-count]').forEach(e=>{e.textContent=n;e.style.display=n?'inline-flex':'none'})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){let box=document.getElementById('items'),empty=document.getElementById('empty'),sum=document.getElementById('summary');if(!box)return;let c=get();if(!c.length){box.innerHTML='';if(empty)empty.style.display='block';if(sum)sum.style.display='none';return}if(empty)empty.style.display='none';if(sum)sum.style.display='block';box.innerHTML=c.map(i=>`<div class="item"><div><div class="name">${esc(i.name)}</div><div class="meta">${esc(i.weight)} · ${money(i.price)}</div></div><div class="controls"><button onclick="BholiCart.qty('${i.key}',-1)">−</button><span>${i.qty}</span><button onclick="BholiCart.qty('${i.key}',1)">+</button></div><div class="item-total">${money(i.price*i.qty)}</div><button class="remove" onclick="BholiCart.remove('${i.key}')">Remove</button></div>`).join('');let t=totals();document.getElementById('subtotal').textContent=money(t.sub);document.getElementById('delivery').textContent=t.del?money(t.del):(t.sub?'FREE':'₹0');document.getElementById('total').textContent=money(t.total);let note=document.getElementById('note');if(note)note.textContent=t.sub>=599?'🎉 You qualify for FREE delivery!':`Add ${money(599-t.sub)} more for FREE delivery.`}
function checkout(e){e.preventDefault();if(!get().length)return;let f=new FormData(e.target),c={name:String(f.get('name')||'').trim(),mobile:String(f.get('mobile')||'').trim(),address:String(f.get('address')||'').trim(),pincode:String(f.get('pincode')||'').trim()};if(!c.name||!c.mobile||!c.address||!c.pincode){alert('Please fill all customer details.');return}let t=totals(),msg='*Bholi Spices - New Order*%0A%0A*Customer Details*%0AName: '+encodeURIComponent(c.name)+'%0AMobile: '+encodeURIComponent(c.mobile)+'%0AAddress: '+encodeURIComponent(c.address)+'%0APincode: '+encodeURIComponent(c.pincode)+'%0A%0A*Order Details*%0A';get().forEach((i,n)=>msg+=(n+1)+'. '+encodeURIComponent(i.name)+' - '+encodeURIComponent(i.weight)+' x '+i.qty+' = '+encodeURIComponent(money(i.price*i.qty))+'%0A');msg+='%0ASubtotal: '+encodeURIComponent(money(t.sub))+'%0ADelivery: '+encodeURIComponent(t.del?money(t.del):'FREE')+'%0A*Total: '+encodeURIComponent(money(t.total))+'*%0APayment: To be confirmed on WhatsApp.';window.open(`https://wa.me/${WA}?text=${msg}`,'_blank')}